### ISSUE TITLE
[RFE] Multiple Movie/TV source tabs

### ISSUE THREAD

**Issue by Vallimar** [tinyMediaManager/tinyMediaManager#1]
Any chance of making it possible to create additional movie or tv source tabs, each with their own settings? I ask because I love an option to keep my anime separate from my regular tv episodes. It gets difficult to track them when they are all mixed together. Or maybe just to appease us anime fans, add just a new anime tab that is essentially a clone of the tv one? I'm sure I'm not the only one that would find this to be a useful feature.

**Comment by mlaggner** [comment]
the request for an own anime has been placed some times now, but from my point of view it does not differ enough from regular TV shows to create an own module for it (creating an extra module would add ~ 30% - 40% of the current tinyMediaManager code).

If you only want to separate anime from the rest, I would recommend you to make an extra anime installation of tinyMediaManager (since it is no problem to have several tinyMediaManager installations in parallel)

**Comment by Vallimar** [comment]
It shouldn't need it's own module, wouldn't it be possible to use the existing code, just with a different configset? Though I haven't looked at the source enough to see if it's already module enough to allow plugging in a new tab so maybe it's too much effort for the current design.

Thanks for the alternate suggestion though!

**Comment by mlaggner** [comment]
to be honest, there are too much pieces of code which reference to the TV show settings - that won't be changeable without massive work.
