### ISSUE TITLE
Feature Request: Initiate library update in Kodi from TMM

### ISSUE THREAD

**Issue by Dracoster** [tinyMediaManager/tinyMediaManager#123]
Would this be possible?
Would be nice to not have to remote into my fileserve (which is also running Kodi and mySQL for database purposes) to update the library.

**Comment by mlaggner** [comment]
is possible over the JSON interface, already on our ToDo list, but there has been no resources to implement that

**Comment by msdos** [comment]
IIRC, a single call like `curl --data-binary '{ "jsonrpc": "2.0", "method": "VideoLibrary.Scan", "id": "mycall"}' -H 'content-type: application/json;' http://kodi:@localhost:8080/jsonrpc` starts the library update. The GUI needs to be updated to receive username, password, port and host to create this call (since my example is using everything that's default).

**Comment by msdos** [comment]
Sorry, my last message wasn't really useful and I've just seen https://github.com/tinyMediaManager/tinyMediaManager/issues/335. I actually think this can be closed so the Kodi discussion can be there.

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
