### ISSUE TITLE
Video format detection

### ISSUE THREAD

**Issue by CyberC123** [tinyMediaManager/tinyMediaManager#131]
__What TMM version are you using?__
2.9.3-SNAPSHOT

__release, pre-release, nightly, or directly from GitHub/branch?__
NIGHTLY

__What is the actual behaviour?__
I have Full-HD movies with a height of 1088 instead of 1080.
tMM assumes that is a 4k movie instead of 1080p.

__What is the expected behaviour?__
Video format = 1080p

**Comment by myron0815** [comment]
mhm... yes.
We could blur these values a bit, so that slightly out of spec file still fall in this category (+/- 1% or so)
Have to think about that.

But keep in mind, that Kodi has the same (fixed) implementation of these values.
So when you play it there, it will update internal to 4k as well.
But at least it will be correct for TMM :)
