### ISSUE TITLE
Feature Request: Multiple video format versions under same folder

### ISSUE THREAD

**Issue by sanghviharshit** [tinyMediaManager/tinyMediaManager#134]
__What TMM version are you using?__
2.9.2

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
Gives error: Failed to rename: Destination '<folder>' already exists.

__What is the expected behaviour?__
Should be able to rename multiple versions of same video file under same folder.

__Steps to reproduce:__
- first
Have a movie in a folder.

- second
Try to add another version of the same movie, from cleanup/rename option

__Additional__
Have you attached the Logfile from the day it happened?
- No
Your Operating system? (win/mac/linux? version?)
- Mac

I am trying to follow the media preparation [guide from Plex for multi version movie](https://support.plex.tv/hc/en-us/articles/200381043-Multi-Version-Movies)

**Comment by myron0815** [comment]
Yes, having same movie in different editions/resolutions, you have to make sure, that the FOLDER renaming pattern is unique.
We don't merge 2 movies into same directory; we strive to keep "one movie (variant) per folder".

Whilst this was intentional on your side, it is mostly unintentional (because of a wrong renamer pattern); so we better break here, before doing some wrong stuff...
