### ISSUE TITLE
No relative paths in NFO despite download option

### ISSUE THREAD

**Issue by CySlider** [tinyMediaManager/tinyMediaManager#149]
__What TMM version are you using?__
2.9.3.1

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
```
<actor>
        <name>Shun Oguri</name>
        <role>Captain Harlock (voice)</role>
        <thumb>http://image.tmdb.org/t/p/w185/nQC5diyl25qS8qLsdMxTzafjnHn.jpg</thumb>
</actor>
```

__What is the expected behaviour?__
```
 <actor>
        <name>Shun Oguri</name>
        <role>Captain Harlock (voice)</role>
        <thumb>.actors/Shun_Oguri.jpg</thumb>
</actor>
```

__Steps to reproduce:__
- Tick "Download actor images to .actor" then scrape a movie

__Additional__
This happens for everything that is downloaded. Though it is now available locally in the movei.nfo it is still pointing to the remote location.

Am I missing something?

**Comment by myron0815** [comment]
IIRC, the local files are always used, regardless if they are written into NFO or not.
And only when there's no image found, Kodi will interpret the thumb url.
At least, it was the case with Kodi 16 :)

So i would say this is intentional.
And only if Kodie tries to download this file, although a local one is available.... the it's a bug...
