### ISSUE TITLE
[Feature Request] Please add an Univers Tag 

### ISSUE THREAD

**Issue by Mannshoch** [tinyMediaManager/tinyMediaManager#186]
With the Universe Tag you could also Manage the Marvel universe. Inside of the Marvel universe are som Movie sets like the Iron Man (with movie 1,2,3) and Thor, etc. and Maybe also add TV series to it like Agents of Shield

If possible Please add also add the posibility to add a fiction date so you could arrange Movies in a Historic manner. 

The big problem maybe here. there is no database in Internet which collect also this information and allow people to share these details.

**Comment by ProIcons** [comment]
I'm not sure that we wanma go down this way. We take data from some datasoucers such like tmdb, we process them and display them to you in a pretty way. Since there is no service that provides these kind of data, to do a feature like that requires a lot of maintenance which we don't currently have the time to give.
Beside that, tinyMediaManager will not host any kind of service that will provide any kind of data.

**Comment by myron0815** [comment]
Since you already wrote the name "tag", please simply use tags for such a feature.
Or maybe MovieSets, grouping that a bit (but a movie can only have ONE set; but having multiple tags...)
