### ISSUE TITLE
Multiple Episode and Split Episodes?

### ISSUE THREAD

**Issue by Kiina** [tinyMediaManager/tinyMediaManager#187]
I recently bought a DVD of a series and just ripped the complete ISO to my NAS. Every DVD has 4 Episodes. But I can't find a way to make a multi-episode nfo. I can multi-select on the `Search Episode` but that seems to do nothing (it seems like you can do it from file names but not manual). The DVD has chapter markers but it probably wouldn't be a problem to just say where the new episode starts. Also many shows recently started to split into two parts so they can run commercials inbetween. If I record them I have 2 files but tvdb treats them as one Episode for the most part. I always used ffmpeg to join them but having the option to make a split episode nfo would be good to.

Kodi seems to support this:

http://kodi.wiki/view/NFO_files/TV_episodes
http://kodi.wiki/view/TV_Shows_(Video_Library)#Multi-episode

**Comment by buhtz** [comment]
This doesn't sound like a bug. It sounds like a support question. ;)
Can you be more specific. Show a directory listing of your NAS plesae.
What do you mean with "ripped"? Are there ISO-files on your NAS or the internal structure of the DVD (VIDEO_TS/...) or avi-files?

**Comment by ProIcons** [comment]
Neither tinyMediaManager neither Kodi neither Plex or any known Media Center/ Media Manager tool currently support multi episode nfo. 
The architecture is "TV Series/Season/Episode" As of now there's not functionality to scrape multiple Episodes from a Single ISO/File in general. This requires file parsing, which it is time consuming, and media dependent. It needs a lot of work to accomplish that. The System currently is working by the file's name. We get it process it scrape from a datasource the processed name, and we get your result. If a media has more than one episode in it, we are not in position to tell, because beside from the basic Media Info we get from the MediaInfoLib, we are not parsing further any file. Either way, since this isn't a high priority task at the moment, there will be a discuss about this issue at the Version 3.

**Comment by Kiina** [comment]
> neither Kodi neither Plex or any known Media Center/ Media Manager tool currently support multi episode nfo.

Wait then why does it say so in the linked kodi wiki?

> If a media has more than one episode in it, we are not in position to tell

well but I don't even have the possibility to tell tmm it myself without renaming the file. The thing that should probably be possible if it is with filenames is that you can select multi episodes under the edit tv show episode window. At least that is how I would imagine it to work

**Comment by ProIcons** [comment]
I might be rushed to answer on this one, give me some time to investigate

**Comment by Kiina** [comment]
I just tested it. Took my .iso from the DVD, put it in a folder, renamed it:

`Winter Sonata.s01e01.s01e02.s01e03.s01e04.iso`

Added it to Kodi, it is showing 4 Episodes with 1 hour length which is about right. Added it to tmm, it gets recognized as multi episode because of the naming, created an .nfo. Kodi shows it as 4 Episodes but with 4 hours length each (may be a different problem such as missing `epbookmark`). So the support from Kodi and tmm seems given. There is just no way to manually mark files as multi episode if it doesn't get picked up by filenames.

![image](https://user-images.githubusercontent.com/2419591/29265495-90dd06fe-80e1-11e7-8508-e141b4d0618d.png)
I would expect it to kinda work like this if you can already multiselect on this list

**Comment by ProIcons** [comment]
Yeah i found it out yesterday. I needed more time about the duration. Anyway sorry for my mistake im new to tmm. Wait Manuel or Myron to give a more propper answer

**Comment by myron0815** [comment]
yes, kinda that way :)
You have to manually rename your file, to be recognized as multi episode. There is simply no GUI method, to create more episodes out of a single one (you can't multi select, because you don't have the other episodes yet ;)

Dividing the runtime by the amoutn of episodes might be another issue, we could improve... (but Kodi overwrites that anyway on first play)

And no idea, how we could fill `epbookmark` ... or how this will work on DVD isos...

**Comment by Kiina** [comment]
> (but Kodi overwrites that anyway on first play)

Just added it to a nfo and it's still there after first play.

Yeah the support for playback from a specific point on isos seems to be a bit sketchy in kodi (ie not working with epbookmark). So I will probably have to do a remux at some point. But for other formats it seems fine.

**Comment by Kiina** [comment]
@ProIcons did it get closed because it's a wont fix? Also noticed the current filename implementation has some issues. Go Name a file "Testfile.E10.x265.mkv". It will get picked up as E10 and E265 and without changing it to S01E10 you have no chance to get rid of the E265.

**Comment by ProIcons** [comment]
Yeah sorry forgot to add the milestone

**Comment by gfnool** [comment]
Having the epbookmark tag supported would be great, lots of kids cartoons are aired with 2 episodes together and it's annoying to see the 2 episodes on the library without being able to play them from the proper starting point.

**Comment by Rouzax** [comment]
Should this already be implemented in the current 3.0 version

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
