### ISSUE TITLE
.part files appearing after scarping

### ISSUE THREAD

**Issue by heyfrank** [tinyMediaManager/tinyMediaManager#222]
Version: 2.9.5
Build: 2017-10-05 19:26
OS: Windows 10 10.0
JDK: 1.8.0_73 amd64 Oracle Corporation

__What is the actual behaviour?__

Since the 2.9.5 update every time I do a scrape of a tv show or movie .part files start appearing and taking up memory as well. The .part files appear in the tv show's folder, sometimes in the season folder as well.

__What is the expected behaviour?__

Expected behavior is for no .part files to appear, it looks like they're not fully downloading for some reason.

__Steps to reproduce:__

Scrape TV show, .part files appear

__Additional__
Have you attached the logfile from the day it happened?

**Comment by ProIcons** [comment]
Hello, some times, when there's not a lot of disk space, or if a request of a resource fails, .part files remaining in the folder (these are the temporary files getting created to write data on them, and then renaming them on the proper ones when the fetch is complete). While this will be fixed in v3, you have to manually delete them

**Comment by ProIcons** [comment]
Also your java version is outdated, please update it to ensure the proper function of network utils.

**Comment by myron0815** [comment]
We did some error handling, and they should not reappear again.
Thx
