### ISSUE TITLE
Support for folder.jpg

### ISSUE THREAD

**Issue by Hawkynt** [tinyMediaManager/tinyMediaManager#229]
__What TMM version are you using?__
tmm 2.9.5

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
When scraping artwork for shows and seasons, no folder.jpg is generated

__What is the expected behaviour?__
The show directory should contain a folder.jpg with a scaled down version of poster.jpg with a maximum width/height of 256px and correct aspect ratio.

Each season directory should contain a folder.jpg with a scaled down version of season<xy>-poster.jpg with a maximum width/height of 256px and correct aspect ratio. (eg. Season 01/folder.jpg generated from season01-poster.jpg)

__Steps to reproduce:__
- Go and scrape a TV show
- folder.jpg should be generated immediately after the mentioned artwork is downloaded and kept in sync when images are changed

**Comment by mlaggner** [comment]
is that just your wish or is there any need for Kodi (or any other media center) for this?

**Comment by Hawkynt** [comment]
I'm sorry but I think nobody will be able to list ALL media players supporting this de facto standard feature for folder images. Even my old Archos AV 320 supported it back in the old days. Other examples are the mentioned Windows Explorer, WMP, Winamp, Poweramp, most cheap chinese hardware DivX players. 

Just write the contents of poster.jpg in a low-res copy to folder.jpg whenever the user wants to assure, that the correct folder image is used. Use it when writing season posters, show posters and posters for folder-based movies or movie-sets.

It's less lines of code as this discussion ...

**Comment by ProIcons** [comment]
> I'm sorry but I think nobody will be able to list ALL media players supporting this de facto standard feature 

To be clear, i asked for Media Centers you used and know that implement this feature.

> Just write the contents of poster.jpg in a low-res copy to folder.jpg whenever the user wants to assure, that the correct folder image is used. Use it when writing season posters, show posters and posters for folder-based movies or movie-sets.
> 
> **It's less lines of code as this discussion ...**

User feedback and discussion is very important to develop a feature. As we clearly hadn't the idea of doing that, we are asking exactly all the implementation details and also other software implements already this feature to have the correct idea of what you are asking. A huge problem on software development is always communication.

I won't speak directly for tMM but generally for Software Companies having clients ask them to develop a software. While the client has always the correct idea on their minds, they don't express it always as they want it , or express it with less details thinking that everything else they said are enough to fully understand what they ask. Which most of them time is not happening, thats why there are dozens of revisions till the final product.

Not implying this is the case really, we really need to fully understand what you ask. Believe me there's always time for communication. It's better to over discuss something, rather than implementing it way differently than implied. 

To proceed with an add-in feature we need to ensure that this feature will be useful for more than one user and that add-in feature will be useful. We have an agenda with things needed to be completed so every suggested idea is being discussed and if agreed to be implemented, is being pushed on a queue based on it's priority. 

Having said that, thank you for your examples we will be having a look at it, and will let you know as soon as possible we figure out what to do.

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
