### ISSUE TITLE
Scanning Data Source Re-Checks "3D" on 2D Versions of 3D Movies

### ISSUE THREAD

**Issue by EarthBoundX5** [tinyMediaManager/tinyMediaManager#231]
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1524254/tmm_logs.zip)

Version: 2.9.5
Build: 2017-10-05 19:26
OS: Windows 10 10.0
JDK: 1.8.0_144 amd64 Oracle Corporation

__What is the actual behaviour?__
When scanning a data source that contains a 2D version of a normally 3D movie, the "3D" attribute gets checked.  If unchecked to correct issue, this attribute will get re-checked again after next scan of data source.

__What is the expected behaviour?__
When the 3D attribute is unchecked the the video file has no 3D metadata, it remains unchecked after a data source scan.  I would expect this type of thing to only get re-checked during a re-scrape of the movie's data, in which case having to uncheck again would be an acceptable adjustment.

__Steps to reproduce:__
1. Scan Data Source with 2D Version of 3D Movie (ex Silent Hill Revelation 3D, Piranha 3D, Piranha 3DD, Texas Chainsaw 3D, Jackass 3D, Found Footage 3D)
2. Uncheck 3D attribute of 2D Version of 3D Movie
3. Scan Data Source
4. See Previously Unchecked 3D attribute get Re-Checked for 2D Versions of 3DMovies

__Additional__
Have you attached the logfile from the day it happened?

**Comment by ProIcons** [comment]
It might be a conflict between the title and parsing of the media file. Will br checking this out.

**Comment by myron0815** [comment]
mhmm.. yes.
Has some historical background:
When updateing datasource, the associated movie object gets the 3D flag because of the filename.
In more recent versions of TMM, we use mediaInfo to additionally detect 3D on every video file.

So these 2 (kinda independent) settings overlap sometimes.
But mediaInfo does not always detect this correct, so we need an additoinal flag sometimes.
We might remove the former, in favor up being able to manually set it on video files...

Another thing.
Why do you have 3D in title/filename, when it's not a 3D movie?
even Kodi as fallback would interpret this falsely as 3D....

**Comment by EarthBoundX5** [comment]
Thanks for the reply and understanding of the issue.  My personal opinion
would be to rely on the mediainfo and forgo the name...unless you can do a
compare against the actual movie title to exclude random situations like
those I described...which leads into my answer for your question...

The movies I mentioned have 3D in the title from the scraped source, I did
not intentionally name them as such; TMM chose that name because the it was
the name it scraped.

Thanks again,
EarthBoundX5
