### ISSUE TITLE
[Feature Request] Relative path to '.actors' directory in nfo

### ISSUE THREAD

**Issue by RKaczmarek** [tinyMediaManager/tinyMediaManager#255]
__What TMM version are you using?__
2.9.7

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
Even if downloading actors pics is activated and they are stored in '.actors' directory, the nfo for kodi contains the url to any pic source like amazon or tmdb.

__What is the expected behaviour?__
Would be nice to have the relative path to the actors pic in the '.actors' directory instead.

Maybe there should be an '.actors' directory for tv shows too. One for the whole tv show and relative paths to the pics for every episode nfo.

__Steps to reproduce:__

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
Windows 10

**Comment by myron0815** [comment]
Well, yes, this is intentional :)

Kodi always utilizes local files first.
It always searches for `./actors/<firstname> <surname>.jpg`
Since you have downloaded them - no problem.

But when you don't have local files, the NFO is considered.
And there we have all the good and working urls for Kodi :)

TBC: TvShows

**Comment by RKaczmarek** [comment]
nice. thnx for info. can be closed then...
