### ISSUE TITLE
Renamer is moving files to .deletedByTMM

### ISSUE THREAD

**Issue by markbsigler** [tinyMediaManager/tinyMediaManager#274]
__What TMM version are you using?__

v2.9.8  2018-02-08 11:23
Media files are on SMB/CIFS NAS

__release, pre-release, nightly, or directly from GitHub/branch?__

Release, installed with brew cask

__What is the actual behaviour?__

Renamer is moving files to .deletedByTMM
Leaves the directory, but moves most if not all files. tbn file remains, but others moved.
Media files mp4 or mkv moved, thus deleting from database

__What is the expected behaviour?__

If there is a naming conflict, leave files intact

__Steps to reproduce:__
- first
- second
- ...

Update movies, including scrape. 
Manually rename movies. Do not have auto rename set in config.
Doesn't seem to affect tv, just movies.
[tmm.2018-03-26.0.log.gz](https://github.com/tinyMediaManager/tinyMediaManager/files/1849417/tmm.2018-03-26.0.log.gz)
[tmm.log](https://github.com/tinyMediaManager/tinyMediaManager/files/1849419/tmm.log)

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

macOS 10.13.3

Seems to be doing some kind of "clean up". 
Doesn't seem to matter what the filenames are. No special characters, etc.

**Comment by shaybc** [comment]
**What TMM version are you using?**
v2.9.8 2018-02-08 11:23 Media files are on External USB drive (4TB Western Digital)

**release, pre-release, nightly, or directly from GitHub/branch?**
Release, simply downloaded and moved to application folder

**What is the actual behaviour?**
Renamer is displaying deleted file as if it is the only file to rename (since it is in the db), and all other files as does not exist in the db (therefor not renamed but deleted)

**What is the expected behaviour?**
name of movie folder and file renamed as set-up in the settings pattern, while understanding the deleted file is not there any more and not to remove the existing files due to rename process

**Steps to reproduce:**
	•	add a source folder to movies datasource
	•	set the folder and file renamer pattern to $T ($Y)
	•	check V on the “Replace non ASCII characters…”
	•	all other options in Renamer are unchecked
	•	add a downloaded movie to the folder (folder with a movie file inside it)
	•	filter by the certain datasource  in the “filter by” panel
	•	right click the movie and press “search & scrap selected movie(s) - force best match
	•	delete some files from the movie folder (VIA finder, i deleted the sample.mp4) 
	•	right click the movie and press “update selected movie”
	•	the deleted file should still appear at the movie detailes panel
	•	right click the movie and press “Rename/cleanup selected movie(s) - dry run
	•	the panel will display the folder with the deleted file with a ‘-‘ (minus sign) next to it in the “old file names” table, rest of the files will not have any sign next to it
	•	the panel will display the folder with the deleted file with a ‘+‘ (plus sign) next to it in the “new file names” table, rest of the files will not have any sign next to it
	•	click the “rename” button (to commit changes)
	•	the file will be deleted and the “Tools -> Show error log” should display a line similar to this:
WARN o.t.core.movie.tasks.MovieUpdateDatasourceTask2 - dir /User/…/Movie folder not in hashset, but on hdd!

**Additional**
I use macOS 10.13.3
i am pretty new user with TMM (few days), but amazed from all the features, the renamer feature is a real time saver,
i had experienced it myself yesterday but i cannot find the deleted file anywhere (not in the trash, or as hidden, from command line or finder or with spotlight, absolutely nowhere)
and it is really unpleasant to re-download movies that i had barely found seeds to,
more then that it cause me to not trust TMM
the most important feature of TMM for me is the re-namer, since most of the other wonderful features i get from Plex.


**About my Mac:**
![screen shot 2018-03-30 at 03 52 26](https://user-images.githubusercontent.com/8535905/38120580-8f271530-33d2-11e8-8f3b-51b0edf713be.png)


**TMM Log Screen:**
![screen shot 2018-03-29 at 02 12 44](https://user-images.githubusercontent.com/8535905/38120597-a0eb8508-33d2-11e8-9cb2-f85277030d54.png)


**Finder showing the folder empty (notice the open triangle next to the name, and the size still say 1.2G):**
![screen shot 2018-03-29 at 02 12 29](https://user-images.githubusercontent.com/8535905/38120624-d6fc9934-33d2-11e8-80aa-fb954ba91354.png)


**Terminal displaying the same folder with only 102 bytes:**
![screen shot 2018-03-29 at 02 12 18](https://user-images.githubusercontent.com/8535905/38120641-facc09f8-33d2-11e8-932b-ce2a7d735377.png)

**Comment by mlaggner** [comment]
Thanks for the report - I'll try to understand what happened..
But unless you have ticket the setting `Delete trash/backup folder on exit` AND exited tmm after renaming, everything is fine (the files have been moved to the datasource/.deletedByTMM folder)
Could it be, that you actually renamed the movie only on the case of some characters? I only saw that the File `Mary_And_The_Witch's_Flower_(2017)-720p-DTS-6ch.mkv` should have been renamed to `Mary_and_the_Witch's_Flower_(2017)-720p-DTS-6ch.mkv`.. this in combination with the OSX file system (which is not case sensitive per default) could lead to a special case in file handling (in fact `Mary_And_The_Witch's_Flower_(2017)-720p-DTS-6ch.mkv` is `Mary_and_the_Witch's_Flower_(2017)-720p-DTS-6ch.mkv`).

the only other theoretical case for auch a behavior could be that you removed MKV from video file types and tmm has cleaned up that files after renaming (but I doubt you have done that)

**Comment by markbsigler** [comment]
@miaggner thanks for the quick follow up. 

Don't have Delete.. on Exit set, nor removed MKV from video file types.

Perhaps macOS case insensitive was a factor.

However, I wouldn't expect renaming to result in a move to .deletedByTMM folder. If the file(s) can't be renamed, they should be left intact, as-is, in-place, not moved. The only use case in which I would expect a move would be on Delete selected movie(s) (DB + file).

Separate, but perhaps related question as to renaming. Why are .TBN files moved to .deletedByTMM rather than renamed to thumb? I don't have Enable extra artwork for any additional types. Further, I note that fanart files are also moved and replaced, rather than renamed.

**Comment by mlaggner** [comment]
this was not intentional; as part of the cleanup process we delete _old_ files prior to renaming (if they even exist).
And there is a special case on the OSX file system: whereas the java implementation of Path respects file cases (where Mary_And_The_Witch's_Flower is **NOT** Mary_and_the_Witch's_Flower) the implementation of Files.exist() respects the behavior of the underlying file system (where Mary_And_The_Witch's_Flower is Mary_and_the_Witch's_Flower) - in this case the new file after renaming was the old one before renaming even if the case changed..
I've included a fix where we check the existence of the old file in a different way
