### ISSUE TITLE
Issue with a "-" in filename, IE Stargate SG-1

### ISSUE THREAD

**Issue by BDaddyG** [tinyMediaManager/tinyMediaManager#305]
Version: 2.9.12
Build: 2018-05-29 18:55
OS: Linux 4.13.0-41-generic
JDK: 1.8.0_171 amd64 Oracle Corporation

__What is the actual behaviour?__
Updating data source with a TV show with a '-' (dash) drops the text from the dash to whitespace, which then causes search and scraping to fail. 

For example: 
Filename:  Stargate SG-1 - S04E01 - Small Victories.mkv
When the data source is updated it is listed as:  Stargate SG Small Victories
When a search and scrape is performed: Stargate Sg 1   is shown in the search box; notice the missing dash "-" and case change (don't know if that makes a difference or not)

Replacing the space between "Sg" and "1" with a "-" allows for a successful search and scrape.  

__What is the expected behaviour?__
Successful data source update and search / scraping lookup.

__Steps to reproduce:__
Have a file named:  Stargate SG-1 - S04E01 - Small Victories.mkv
Update data source
Perform "Search and scrape of selected TV Show"

__Additional__
Have you attached the logfile from the day it happened?

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2063485/tmm_logs.zip)

Thanks for the program and your work on it!

**Comment by myron0815** [comment]
well, yes.
Since a dash is always a delimiter, we won't add your tv show with correct name (derived from show folder name). But you only need to search for TV show once, so this series requires a bit manual interaction. Adding additional files is not affected, we always use the S/E numbers for it.

The fix - implementing some exceptions on common names - is kinda hard, and stands in no relation to its use here...
And we never can automate 100%, but 99,9% is still fine for me ;)
