### ISSUE TITLE
NFO rewrite on trakt sync

### ISSUE THREAD

**Issue by thwaller** [tinyMediaManager/tinyMediaManager#338]
Version: 2.9.12-SNAPSHOT - PRE-RELEASE
Build: 2018-05-28 13:37
OS: Linux 4.15.0-23-generic
JDK: 1.8.0_171 amd64 Oracle Corporation

__What is the actual behaviour?__
When doing a sync to trakt using the ones selected for collected and watched, tMM rewrites the NFO for all selected movies, regardless if there are changes or not. Is that needed for some reason? The reason for my asking is that running a sync of a list causes all those files to change, which in turn causes my backup to consider all the files changed. This is not the end of the world as the NFO files are small, but it does impact 100s and in some cases 1000s of files by doing this.

__What is the expected behaviour?__
Only rewrite NFO is there is a need to / there is a change to write

**Comment by myron0815** [comment]
Hmm... we should only write new NFO, when something has changed.

Changes are:
- updated/additional IDs on Trakt side (like tmdb, tvdb, tvrage) which we currently do not have set
- hasBeenWatched and/or lastWatched date differs from ours
Only if that has changed, the we write new NFO...

Need to test/debug further if we have an error here... but it should be definitely not the case, to alter them all (there can't be that much changes i guess)

Maybe you can check the logs for some "Trakt" entries, there should be some statistics what we have done...

**Comment by thwaller** [comment]
Thanks for the reply. I will look into this further. I was unaware that the NFO would be updated for anything other than the watched status, as that is the action I am initiating. I understand what you are saying though, and I will check on this.

**Comment by thwaller** [comment]
I am closing this issue for now. Given the information provided, I need to do some testing and do not want to forget and leave an open issue. Should I find the actual working to be different than described, I will comment again and request this to be reopened.

**Comment by mlaggner** [comment]
the problem is, that we never know what information actually is in the NFO file unless we read it before and compare everything with the actual NFO file we would write.
This would need a disk read, parse and compare every time we wand to write the NFO file (and we have several _save points_ to make sure everything is up to date in the NFO)..
I'd guess that writing the NFO file at our save points is much easier/quicker/fail save than doing the comparing all the time - just for preventing the backup to kick in..

**Comment by myron0815** [comment]
It's a 2-way sync.
We not only get data from trakt;
You can set it within TMM and we sync it to Trakt.
Since TMM might not be the only program syncing your trakt account...

The sync workflow is documented here:
https://trakt.docs.apiary.io/#reference/sync
This is the way we have implemented it.

But yes, there should be barely changes.
I'll reference the source here: https://github.com/tinyMediaManager/tinyMediaManager/blob/master/src/main/java/org/tinymediamanager/scraper/trakttv/TraktTv.java
We set the "dirty" flag when we encounter a changed id, or something withe the watched date.
I assume there could be an error...

**Comment by myron0815** [comment]
Might have found something.

We always compare the "watched date" with ours.
Since TMM (and Kodi) do not save the date, it always resulted in rewriting NFO file.
Please test for movies & TV.

Thx for reporting

**Comment by myron0815** [comment]
There was an error on "watched state sync".
After a TMM restart, the NFO was again written again after a trakt sync.
You could check the last modification date on an NFO... and it should stay as is now...
