### ISSUE TITLE
Display language names in UI language?

### ISSUE THREAD

**Issue by raffishtenant** [tinyMediaManager/tinyMediaManager#347]
Version: 2.9.12
Build: 2018-05-29 18:55
OS: Mac OS X 10.13.1
JDK: 1.8.0_161 x86_64 Oracle Corporation

__What is the actual behaviour?__

Language names (e.g. when scraping) are displayed as they would read in the language itself.

__What is the expected behaviour?__

It's a small thing, but as a future enhancement, perhaps there could be an option to display language names in whichever language has been selected for the UI, e.g. if the UI language is English, "Suomi" would instead display as "Finnish" in popups etc. I realize it's one more thing to localize, and possibly a PITA, but it would be so helpful when it's necessary to scrape in a title's native language to find a match. (Potentially even better if scraping could be language-agnostic, though my suspicion is that this is more a limitation of the various DB APIs than it is of TMM.)

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
the problem here is, that we only have the language names in their native version. See https://github.com/tinyMediaManager/api-scraper/blob/3484749d9ef77f95353233184220ca73e204e477/src/main/java/org/tinymediamanager/scraper/entities/MediaLanguages.java#L31

so without a greater restructure here we won't be able to display that.. But on the other side: if you want to scrape in another language, you probably are able to read the native name too ;)

so that will probably not fixed

**Comment by mlaggner** [comment]
just found a way to take the translation from java itself..
in v3 the scraper language will be displayed in the UI language if possible (otherwise in native language)

should work in v3 from tomorrow
