### ISSUE TITLE
Artwork scraper not scraping

### ISSUE THREAD

**Issue by Zw3rv3r** [tinyMediaManager/tinyMediaManager#369]
Version: 2.9.13
Build: 2018-07-23 18:42
OS: Linux 4.15.0-32-generic
JDK: 1.8.0_181 amd64 Oracle Corporation

__What is the actual behaviour?__
The artwork scraper seems unable to connect with the artwork provider.

__What is the expected behaviour?__
Artwork being found and scraped ath the provider.

__Steps to reproduce:__
1) Right-click select movies without artwork
2) Chose "Download missing artwork..." (in English, I'm Dutch)
3) Scraping fails after apr. 100ms with the the attached log failure messages

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs_NO_PW.zip]

**Comment by mlaggner** [comment]
fanart.tv responds with a `404 Not Found` - so there is probably nothing for the movie you want to scrape OR there is a temp. network failure at fanart.tv..

**Comment by msdos** [comment]
Do you think it's feasible to create a feature that retries for that image for x seconds (maybe a parameter in tinyMediaManager configuration)?

**Comment by mlaggner** [comment]
a retry is already implemented in v3 https://github.com/tinyMediaManager/tinyMediaManager/blob/2ec6613e4d4abb529227678497c26ff5166bb4f0/src/main/java/org/tinymediamanager/core/tasks/MediaEntityImageFetcherTask.java#L134
an option is not planned, since we want to make tmm easy/small - and we're against having too much settings

**Comment by mlaggner** [comment]
a retry will be in v2 in the next release
