### ISSUE TITLE
TMMv3 java interrupted ... and rescrape graphics

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#399]
Version: 3.0-SNAPSHOT
Build: 2018-09-25 07:09
OS: Windows 7 6.1 Polish
JDK: 1.8.0_181 amd64 Oracle Corporation

1. Sometimes when I download extra graphics the following information appears which I do not understand. The program seems to work normally after closing the window.

[TMMv3 java interrupted.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/2417337/TMMv3.java.interrupted.txt)

2. When the download of some graphics fails, subsequent attempts do not give any response:
- I select a few movies to edit
- I download the graphics - the progress bar shows that the download is working - then the information shows that the download has failed
- I am re-downloading the graphics - there is no progress bar that the program works - the graphics do not save in the movie folder.

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2417407/tmm_logs.zip)

thank you in advance for your help

**Comment by myron0815** [comment]
We have several errors here:

1) is a simple download interrupt.
Eg the server ends the connection, or you closed the "image chooser" while it was still downloading some previes - you can ignore that

2) fanart.tv also throws some errors - some of their servers _still_ have invalid SSL certificates.
There should be a new setting to ignore such - gerneal / system settings IIRC

3) since we have some url caching, it might be also that case of beeing not able to redownload such images - have to check

**Comment by Zwanzig2** [comment]
OKAY
1. this is not a problem :)
2. Disable SSL certificate in settings??
3. hmm ... this is a problem, how to change the graphics in this case. Can you disable url caching ??

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
