### ISSUE TITLE
Request: VideoStation .vsmeta file support

### ISSUE THREAD

**Issue by soywiz** [tinyMediaManager/tinyMediaManager#456]
Synology's VideoStation has a propietary `.vsmeta` file format instead of reading `.nfo` files or even reading `poster.ext` for tvseries.

I have written some code in kotlin using my libraries to read and write those files. Now I'm synchronizing my `.nfo` files into `.vsmeta` files manually via code, but would be nice if they are supported by tinyMediaManager directly.

I can port the existing code to Java if you find this interesting.

The current kotlin code (released under public domain, so you can use it):
https://gist.github.com/soywiz/2c10feb1231e70aca19a58aca9d6c16a

**Comment by myron0815** [comment]
Owning a Syno myself, i've also reversed the vsmeta format a few years back.
https://github.com/tinyMediaManager/tinyMediaManager/blob/master/src/main/java/org/tinymediamanager/thirdparty/VSMeta.java
It is kinda hackish, and not fully complete, but it was enough for reading some basics, and decode the meta json et all.

Generating a complete VsMeta is another story.
And i'm unsure, if we understand the format fully, and to write it correctly.
I struggled with bigEndian/littleEndian formats of other DiskStations.
And if THEY change something, WE won't get a chance to fix it in a timely manner, and therfor mess the user's library files...
Another story:
If we write the files, WHEN are they read back to their database?
Does changing a file and a update(?) of a single movie work there?

So, i'm not yet completely satisfied with writing it, but i will definitely check your code (which looks much cleaner/complete)... also never read a Kotlin variant - so, yes, help always appreciated :)
Since we probably won't add anything to TMM v2, you might want to switch to https://gitlab.com/tinyMediaManager/tinyMediaManager for v3...

**Comment by soywiz** [comment]
Actually I was able to parse all the nfo files I was able to produce using Videostation. So it is pretty complete. They should keep compatibility at least in the case you migrate for other version. So reading might break in the future, but writing should continue working.

Looking at your code it seems that you were reading the tags as a single byte and they are also VL (https://sqlite.org/src4/doc/trunk/www/varint.wiki) (there are one or two tags that doesn't fit in 7 bits)
So you can take just 7 bits from each byte, and the upper byte indicates if there are more bytes to read. For example, there is a "-1" for the rating encoded as "FFFFFFFFFFFFFFFFFF01" when no rating is provided, when it is provided you have to divide the value by 10 to get the actual rating.

Until I figured out all the variable length integer stuff I was not able to fully parsing stuff making fully sense.

----

Regarding to littleEndian/bigEndian, I'm not sure, but I hope they have a different magic to differentiate in the case you migrate your hard disk to other NAS.

----

When is it read? Not immediately. I had to remove the folder, and add it again. After that, the index is created and all the vsmeta files read. Not a big deal in my case. The vsmeta files I'm generating are successfully read by my DiskStation without issues including images (poster, backdrop and episode thumb) and all the information. All the tags are known by now for tvshows at least (not reverse engineered movies yet, but shouldn't be too complicated now that I know they are using variable length encoding for all the integers and tags).

**Comment by mlaggner** [comment]
just cleaning up the repo here (since we work at gitlab now)..
we would be happy to use your code, but we do not plan to use/support kotlin for now..

I do not know if myron has some time to migrate your code to plain Java.. Could you create a maven artifact, so we can use it directly?

**Comment by mlaggner** [comment]
I've just copied the conversation here over to gitlab and closing this issue right now:

https://gitlab.com/tinyMediaManager/tinyMediaManager/issues/620
