### ISSUE TITLE
runtime of movies

### ISSUE THREAD

**Issue by Ferdster** [tinyMediaManager/tinyMediaManager#487]
__What TMM version are you using?__3.0.1

__release, pre-release, nightly, or directly from GitHub/branch?__ directly

__What is the actual behaviour?__runtime is taken from mediainfo info durationinseconds, which is sometimes not correct, especially when dealing with BDMV file structures.

__What is the expected behaviour?__include an option to use scraped runtime

__Steps to reproduce:__
- first
- second
- ...

__Additional__
Have you attached the Logfile from the day it happened? files are posted in the kodi forum, see the following post: https://forum.kodi.tv/showthread.php?tid=344796
Your Operating system? (win/mac/linux? version?)windows

**Comment by myron0815** [comment]
changed it, so that we do not write 'durationinseconds' for disc style movies.
Since this seems to be designed for file streams, and whereas a disc has many of them, it might not be so easy to detect this correct. MediaInfo, as well as Kodi, detect/write this currently wrong, so the best solution is to skip that, and the skin has to take the scraped/entered movie runtime...
